sonar.projectKey=opensalestax-magento
sonar.projectName=opensalestax-magento
sonar.projectVersion=0.1.0
sonar.sources=EJOsterberg/OpenSalesTax
sonar.tests=EJOsterberg/OpenSalesTax/Test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/build/**,**/coverage*/**,**/Test/Stubs/**
sonar.test.inclusions=**/Test/Unit/**/*Test.php
sonar.host.url=http://10.32.161.205:9000
